### ISSUE TITLE
Push Notifications API Support

### ISSUE THREAD

**Issue by r0kk3rz** [QMatrixClient/libqmatrixclient#199]
It would be great to add support for this Matrix API
https://matrix.org/docs/api/client-server/#!/Push32notifications/getNotifications

As it would allow the creation of a notifications service for use with Mobile devices and Desktop Notifications

**Comment by KitsuneRal** [comment]
Depends on KitsuneRal/gtad#24 (the interface of this API  is extensive enough that I don't fancy writing it by hand, and GTAD has to learn protecting identifiers from clashing with reserved words anyway).
I'll take a look if this can be prioritised.

**Comment by KitsuneRal** [comment]
Fixed as of fe4afda065fc9a1db64fd8032bad4e10bff3d020

**Comment by Flohack74** [comment]
I consider this as not fixed. At least the call to https://matrix.org/docs/api/client-server/#!/Push32notifications/postPusher needs to be implemented to speak about real push notifications. This is more like pull notifications. Nice but not what mobile devices need.

On a mobile device you typically do not want to have the App doing all the heavy lifting and actually polling the list of notifications from the server. Even worse, in Ubuntu Touch there are no background activities allowed for Apps, putting them to sleep and preventing any of that local processing.

The only way for notifications is via push from outside. So libqmatrixclient needs to realize an API call where we can submit the push server key, and the other parameters, which in turn will then hopefully trigger the callback from the Matrix server to our push server, and then to the device.

On the device, a special small executable is then allowed to run, transforming the Matrix notification into a local one, and finally alerting the OS to show a popup and play a sound.

Thats push notifications in a nutshell. Android and iOS work in a similar way.

**Comment by KitsuneRal** [comment]
As discussed in the room, support of pushers configuration is already in the library, [please upgrade](https://github.com/uMatriks/uMatriks/issues/67).
